remove legacy code

diff --git a/src/runtime_src/core/tools/xbutil2/xbutil b/src/runtime_src/core/tools/xbutil2/xbutil
--- a/src/runtime_src/core/tools/xbutil2/xbutil
+++ b/src/runtime_src/core/tools/xbutil2/xbutil
@@ -21,6 +21,14 @@ XRTWARP_PROG_ARGS_size=0
 XRTWRAP_PROG_ARGS=()
 while [ $# -gt 0 ]; do
     case "$1" in
+    # Indicates that the legacy was specified
+	-legacy|--legacy)
+	    echo "--------------------------------------------------"
+        echo "Error: Obsoleted option"
+        echo "       The --legacy option is no longer supported."
+        echo "--------------------------------------------------"
+        exit 1
+	    ;;
 	# Copy the options the remaining options
 	*)
 	    XRTWRAP_PROG_ARGS[$XRTWARP_PROG_ARGS_size]="$1"
