fixes

diff --git a/src/CMake/config/postinst-aws.in b/src/CMake/config/postinst-aws.in
--- a/src/CMake/config/postinst-aws.in
+++ b/src/CMake/config/postinst-aws.in
@@ -4,22 +4,24 @@ if [ -n "`dkms status -m xrt-aws -v @XRT_VERSION_STRING@`" ]; then
     modprobe -r awsmgmt
 
     echo "Unregistering old XRT Linux kernel module sources @XRT_VERSION_STRING@ from dkms"
-    dkms remove -m xrt-aws -v @XRT_VERSION_STRING@ --all > /dev/null 2>&1
+    res=$(dkms remove -m xrt-aws -v @XRT_VERSION_STRING@ --all)
     if [ $? -ne 0 ]; then
-        echo "Error: 'dkms remove -m xrt-aws' failed"
+        echo "Error: dkms: $res"
     fi
     find /lib/modules -type f -name awsmgmt.ko -delete
     find /lib/modules -type f -name awsmgmt.ko.kz -delete
     find /lib/modules -type f -name awsmgmt.ko.xz -delete
-    depmod -A > /dev/null 2>&1
+    res=$(depmod -A)
     if [ $? -ne 0 ]; then
-        echo "Error: 'depmod -A' failed"
+        echo "Error: depmod: $res"
     fi
 fi
 
+res=$((/usr/lib/dkms/common.postinst xrt-aws @XRT_VERSION_STRING@ "" "" $2) 2>&1)
 echo "Invoking xrt-aws common.postinst"
-/usr/lib/dkms/common.postinst xrt-aws @XRT_VERSION_STRING@ "" "" $2 > /dev/null 2>&1
-if [ $? -eq 0 ]; then
+if [ $? -ne 0 ]; then
+    echo "Error: common.postinst: $res"
+else
     echo "Finished xrt-aws common.postinst"
     install -m 644 /usr/src/xrt-aws-@XRT_VERSION_STRING@/driver/aws/kernel/mgmt/10-awsmgmt.rules /etc/udev/rules.d
 
diff --git a/src/CMake/config/postinst.in b/src/CMake/config/postinst.in
--- a/src/CMake/config/postinst.in
+++ b/src/CMake/config/postinst.in
@@ -6,9 +6,9 @@ if [ -n "`dkms status -m xrt -v @XRT_VERSION_STRING@`" ]; then
     modprobe -r xclmgmt
 
     echo "Unregistering old XRT Linux kernel module sources @XRT_VERSION_STRING@ from dkms"
-    dkms remove -m xrt -v @XRT_VERSION_STRING@ --all > /dev/null 2>&1
+    res=$(dkms remove -m xrt -v @XRT_VERSION_STRING@ --all)
     if [ $? -ne 0 ]; then
-        echo "Error: 'dkms remove -m xrt' failed"
+        echo "Error: dkms: $res"
     fi
     find /lib/modules -type f -name xocl.ko -delete
     find /lib/modules -type f -name xclmgmt.ko -delete
@@ -16,9 +16,9 @@ if [ -n "`dkms status -m xrt -v @XRT_VERSION_STRING@`" ]; then
     find /lib/modules -type f -name xclmgmt.ko.kz -delete
     find /lib/modules -type f -name xocl.ko.xz -delete
     find /lib/modules -type f -name xclmgmt.ko.xz -delete
-    depmod -A > /dev/null 2>&1
+    res=$(depmod -A)
     if [ $? -ne 0 ]; then
-        echo "Error: 'depmod -A' failed"
+        echo "Error: depmod: $res"
     fi
 fi
 
@@ -29,8 +29,10 @@ if [ -e $DRACUT_CONF_PATH ]; then
 fi
 
 echo "Invoking DKMS common.postinst for xrt"
-/usr/lib/dkms/common.postinst xrt @XRT_VERSION_STRING@ "" "" $2 > /dev/null 2>&1
-if [ $? -eq 0 ]; then
+res=$((/usr/lib/dkms/common.postinst xrt @XRT_VERSION_STRING@ "" "" $2) 2>&1)
+if [ $? -ne 0 ]; then
+    echo "Error: common.postinst: $res"
+else
     echo "Finished DKMS common.postinst"
     install -m 644 /usr/src/xrt-@XRT_VERSION_STRING@/driver/xclng/drm/xocl/userpf/10-xocl.rules /etc/udev/rules.d
     install -m 644 /usr/src/xrt-@XRT_VERSION_STRING@/driver/xclng/drm/xocl/mgmtpf/10-xclmgmt.rules /etc/udev/rules.d
@@ -41,6 +43,7 @@ if [ $? -eq 0 ]; then
     modprobe xocl
     udevadm trigger
 fi
+
 
 if [ -z "`dkms status -m xrt -v @XRT_VERSION_STRING@ |grep installed`" ]; then
     echo "****************************************************************"
