suppress dkms and depmod calls to silence weak-modules messages

diff --git a/src/CMake/config/postinst-aws.in b/src/CMake/config/postinst-aws.in
--- a/src/CMake/config/postinst-aws.in
+++ b/src/CMake/config/postinst-aws.in
@@ -1,19 +1,24 @@
 #!/bin/sh
-
 if [ -n "`dkms status -m xrt-aws -v @XRT_VERSION_STRING@`" ]; then
     echo "Unloading old XRT Linux kernel modules"
     modprobe -r awsmgmt
 
     echo "Unregistering old XRT Linux kernel module sources @XRT_VERSION_STRING@ from dkms"
-    dkms remove -m xrt-aws -v @XRT_VERSION_STRING@ --all
+    dkms remove -m xrt-aws -v @XRT_VERSION_STRING@ --all > /dev/null 2>&1
+    if [ $? -ne 0 ]; then
+        echo "Error: 'dkms remove -m xrt-aws' failed"
+    fi
     find /lib/modules -type f -name awsmgmt.ko -delete
     find /lib/modules -type f -name awsmgmt.ko.kz -delete
     find /lib/modules -type f -name awsmgmt.ko.xz -delete
-    depmod -A
+    depmod -A > /dev/null 2>&1
+    if [ $? -ne 0 ]; then
+        echo "Error: 'depmod -A' failed"
+    fi
 fi
 
 echo "Invoking xrt-aws common.postinst"
-/usr/lib/dkms/common.postinst xrt-aws @XRT_VERSION_STRING@ "" "" $2
+/usr/lib/dkms/common.postinst xrt-aws @XRT_VERSION_STRING@ "" "" $2 > /dev/null 2>&1
 if [ $? -eq 0 ]; then
     echo "Finished xrt-aws common.postinst"
     install -m 644 /usr/src/xrt-aws-@XRT_VERSION_STRING@/driver/aws/kernel/mgmt/10-awsmgmt.rules /etc/udev/rules.d
diff --git a/src/CMake/config/postinst.in b/src/CMake/config/postinst.in
--- a/src/CMake/config/postinst.in
+++ b/src/CMake/config/postinst.in
@@ -6,14 +6,20 @@ if [ -n "`dkms status -m xrt -v @XRT_VERSION_STRING@`" ]; then
     modprobe -r xclmgmt
 
     echo "Unregistering old XRT Linux kernel module sources @XRT_VERSION_STRING@ from dkms"
-    dkms remove -m xrt -v @XRT_VERSION_STRING@ --all
+    dkms remove -m xrt -v @XRT_VERSION_STRING@ --all > /dev/null 2>&1
+    if [ $? -ne 0 ]; then
+        echo "Error: 'dkms remove -m xrt' failed"
+    fi
     find /lib/modules -type f -name xocl.ko -delete
     find /lib/modules -type f -name xclmgmt.ko -delete
     find /lib/modules -type f -name xocl.ko.kz -delete
     find /lib/modules -type f -name xclmgmt.ko.kz -delete
     find /lib/modules -type f -name xocl.ko.xz -delete
     find /lib/modules -type f -name xclmgmt.ko.xz -delete
-    depmod -A
+    depmod -A > /dev/null 2>&1
+    if [ $? -ne 0 ]; then
+        echo "Error: 'depmod -A' failed"
+    fi
 fi
 
 DRACUT_CONF_PATH=/etc/dracut.conf.d
@@ -23,7 +29,7 @@ if [ -e $DRACUT_CONF_PATH ]; then
 fi
 
 echo "Invoking DKMS common.postinst for xrt"
-/usr/lib/dkms/common.postinst xrt @XRT_VERSION_STRING@ "" "" $2
+/usr/lib/dkms/common.postinst xrt @XRT_VERSION_STRING@ "" "" $2 > /dev/null 2>&1
 if [ $? -eq 0 ]; then
     echo "Finished DKMS common.postinst"
     install -m 644 /usr/src/xrt-@XRT_VERSION_STRING@/driver/xclng/drm/xocl/userpf/10-xocl.rules /etc/udev/rules.d
diff --git a/src/CMake/config/prerm-aws.in b/src/CMake/config/prerm-aws.in
--- a/src/CMake/config/prerm-aws.in
+++ b/src/CMake/config/prerm-aws.in
@@ -4,10 +4,16 @@ echo "Unloading old AWS Linux kernel modules"
 modprobe -r awsmgmt
 
 echo "Unregistering AWS Linux kernel module sources @XRT_VERSION_STRING@ from dkms"
-dkms remove -m xrt-aws -v @XRT_VERSION_STRING@ --all
+dkms remove -m xrt-aws -v @XRT_VERSION_STRING@ --all > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+    echo "Error: 'dkms remove of xrt-aws' failed"
+fi
 find /lib/modules -type f -name awsmgmt.ko -delete
 find /lib/modules -type f -name awsmgmt.ko.kz -delete
-depmod -A
+depmod -A > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+    echo "Error: 'depmod -A' failed"
+fi
 
 rm -f /etc/udev/rules.d/10-awsmgmt.rules
 
diff --git a/src/CMake/config/prerm.in b/src/CMake/config/prerm.in
--- a/src/CMake/config/prerm.in
+++ b/src/CMake/config/prerm.in
@@ -11,14 +11,20 @@ modprobe -r xocl
 modprobe -r xclmgmt
 
 echo "Unregistering XRT Linux kernel module sources @XRT_VERSION_STRING@ from dkms"
-dkms remove -m xrt -v @XRT_VERSION_STRING@ --all
+dkms remove -m xrt -v @XRT_VERSION_STRING@ --all > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+    echo "Error: 'dkms remove -m xrt' failed"
+fi
 find /lib/modules -type f -name xocl.ko -delete
 find /lib/modules -type f -name xclmgmt.ko -delete
 find /lib/modules -type f -name xocl.ko.kz -delete
 find /lib/modules -type f -name xclmgmt.ko.kz -delete
 find /lib/modules -type f -name xocl.ko.xz -delete
 find /lib/modules -type f -name xclmgmt.ko.xz -delete
-depmod -A
+depmod -A > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+    echo "Error: 'depmod -A' failed"
+fi
 
 rm -f /etc/udev/rules.d/10-xocl.rules
 rm -f /etc/udev/rules.d/10-xclmgmt.rules
